;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-exchange-point-and-mark
        ns-prev-frame
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        mark-whole-buffer
        nonincremental-search-forward
        ns-copy-including-secondary
        ))
